### ISSUE TITLE
Traceback when attempting to display 'Output Devices' page.

### ISSUE THREAD

**Issue by pvaret** [GeorgeFilipkin/pulsemixer#1]
The traceback:

    Traceback (most recent call last):
      File "./pulsemixer", line 1652, in <module>
        main()
      File "./pulsemixer", line 1579, in main
        curses.wrapper(scr.run)
      File "/usr/lib/python3.4/curses/__init__.py", line 94, in wrapper
        return func(stdscr, *args, **kwds)
      File "./pulsemixer", line 1366, in run
        self.display()
      File "./pulsemixer", line 1501, in display
        n = round(len(vol) * line.volume[bartype] / line.maxsize)
    IndexError: list index out of range

When the error occurs, the value of `line.volume` is `[100]` but `bartype` is `1`.

The code might be making an assumption that is incorrect in my particular setup. In my setup, I have a virtual output device where the left and right channels are remixed into a single mono channel. The configuration in ~/.pulse/default.pa to create this device is:

    load-module module-remap-sink master=alsa_output.pci-0000_00_1b.0.analog-stereo sink_name=alsa_output.pci-0000_00_1b.0.analog-stereo-magic_mono channels=1 master_channel_map=front-right
    update-sink-proplist alsa_output.pci-0000_00_1b.0.analog-stereo-magic_mono device.description="Magic Mono"

The traceback disappears when I unload that module. Strangely, it doesn't reappear if I then reload the module manually (with pactl). It's only when the module is loaded at startup time.

**Comment by GeorgeFilipkin** [comment]
Should be fixed by these two commits 16691dc2061bc22719906ac44c93539507bd1f0e cf44b3217b5798b532ac603af2793ba30030c34d

**Comment by pvaret** [comment]
Indeed! I can confirm the issue is fixed for me. Thanks. :)
