### ISSUE TITLE
Cannot start

### ISSUE THREAD

**Issue by alex-theoto** [GeorgeFilipkin/pulsemixer#16]
It doesn't work on ArchLinux.
I get the following error:
`Traceback (most recent call last):
File "/usr/bin/pulsemixer", line 1784, in <module> main()
File "/usr/bin/pulsemixer", line 1696, in main curses.wrapper(Screen().run)
File "/usr/bin/pulsemixer", line 1192, in __init__curses.init_pair(67, 66, -1)_curses.error: init_pair() returned ERR
`
Python version 3.6.0
pulseaudio version 10.0

Pulse is running:
`ps maux |grep pulse
alex       828  1.8  0.4 1660604 12672 ?       -    19:54   0:55 /usr/bin/pulseaudio --daemonize=no 
alex       832  0.0  0.1  82644  3516 ?        -    19:54   0:00 /usr/lib/pulse/gconf-helper 
alex      1581  0.0  0.0  11344  2240 pts/0    -    20:43   0:00 grep pulse 
`

But I get output on --list-sources etc

Any idea? Do I have to specify something?
Thank you.

**Comment by GeorgeFilipkin** [comment]
Looks like your terminal doesn't support 256 colors or you are using AUR version, which gives you fixed 1.1.0 (which is slightly outdated)

Try the latest version from git and do `echo $TERM; tput colors` to check supported colors.

**Comment by alex-theoto** [comment]
You are right. I didn't set any .Xresources for xterm.
Thank you for your help.
