### ISSUE TITLE
How to run setup.py?

### ISSUE THREAD

**Issue by mano1979** [GeorgeFilipkin/pulsemixer#17]
everytime i try to run "python setup.py" i get this error:

`pi@raspberrypi:~/pulsemixer $ sudo python setup.py
**usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied**`

So what do i fill in here? What commands? and global options?

**Comment by GeorgeFilipkin** [comment]
`sudo python3 setup.py install` to install system-wide
`python3 setup.py install --user` to install locally (~/.local/bin)

Or you could install directly from git:
`pip3 install --user git+https://github.com/GeorgeFilipkin/pulsemixer.git`

Or you could download pulsemixer manually, do `chmod +x ./pulsemixer` and put it anywhere you want. It doesn't need any extra files, just this one executable.

**Comment by mano1979** [comment]
Ok that indeed did the trick!
But now when i try to start it, i get this error:
`pi@raspberrypi:~ $ pulsemixer
Traceback (most recent call last):
  File "/usr/local/bin/pulsemixer", line 4, in <module>
    __import__('pkg_resources').run_script('pulsemixer==1.2.0', 'pulsemixer')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1444, in run_script
    script_code = compile(script_text, script_filename,'exec')
  File "/usr/local/lib/python2.7/dist-packages/pulsemixer-1.2.0-py2.7.egg/EGG-INFO/scripts/pulsemixer", line 1796
    sys.exit(print(VERSION))
                 ^
SyntaxError: invalid syntax
`

**Comment by GeorgeFilipkin** [comment]
You are using python2.7, make sure to use python3. You may need to install it first and specify the version directly, i.e. `python3 ./pulsemixer`

**Comment by mano1979** [comment]
I thought i had tried that. Anyway it works! thanks!
