### ISSUE TITLE
New release (1.2.0 or 1.1.1)?

### ISSUE THREAD

**Issue by embik** [GeorgeFilipkin/pulsemixer#18]
Hey there, thanks for creating pulsemixer. I have a minor request to make: I'm a Gentoo user and write my own ebuilds for software I like. I heavily prefer to work with tarballs for various reasons (e.g. checksum verification) and the latest release 1.1.0 doesn't work properly on my system while the current state of master does.

Would you mind to make a minor release so there's a tarball available that contains the fixes that were committed after the 1.1.0 release?

**Comment by ghedo** [comment]
I've been looking into packaging pulsemixer for Debian, and a fresh release would also help me.

**Comment by GeorgeFilipkin** [comment]
Sure thing. 

1.2.0 is out, based on current master
https://github.com/GeorgeFilipkin/pulsemixer/releases/tag/1.2.0

**Comment by embik** [comment]
Thank you very much!
