### ISSUE TITLE
Color currently-selected channel differently

### ISSUE THREAD

**Issue by squigglezworth** [GeorgeFilipkin/pulsemixer#21]
It would be great to have unselected channels in gray-scale while the selected one is in color.

Thoughts?

**Comment by GeorgeFilipkin** [comment]
Sure. I'll take care of it once I have some free time available, which should be in about a month.

Or I'd be willing to accept a patch if you are up for it. Ideally it should be done with a command line argument, something like `--no-color` or `-c --contrast` or even `--color[=NUMBER]` where 0 - disable color completely, 1 - highlight selected, 2 - full-color.

**Comment by GeorgeFilipkin** [comment]
Done.
```
--color n     0 no color, 1 color currently selected, 2 full-color (default)
```

**Comment by squigglezworth** [comment]
Wonderful! Thank you so much :)
