### ISSUE TITLE
Include MIT License in package

### ISSUE THREAD

**Issue by z1lt0id** [GeorgeFilipkin/pulsemixer#25]
Just wondering if you could include a LICENSE file in the repo?  Unfortunately I'd love to package this for void linux but one of the guidelines is that it has a LICENSE file included if it uses the MIT license.

**Comment by GeorgeFilipkin** [comment]
Done.

**Comment by z1lt0id** [comment]
Hey GeorgeFilipkin,

Could you also include it the official 1.3.0 release as well? It's mandatory that the license file be included in the archive when it fetches.

**Comment by GeorgeFilipkin** [comment]
Apparently it is problematic to add something to an already existed release. Would have to forcefully move tags with the risk of breaking stuff. 

Here is a new release with license included: 
https://github.com/GeorgeFilipkin/pulsemixer/releases/tag/1.3.0-license

**Comment by z1lt0id** [comment]
Hi George,

Thanks for this.  I'll upload Pulsemixer to Void today :)
