### ISSUE TITLE
[Request] Allow specifying step-size

### ISSUE THREAD

**Issue by squigglezworth** [GeorgeFilipkin/pulsemixer#31]
It'd be nice to be able to specify the step size for the Shift+Left and Shift+Right volume adjustments.

:)

**Comment by GeorgeFilipkin** [comment]
Yes it would be nice. I think I'll do a proper config file for this and the rest of configurable parts, so not to clutter ENV variables.

I don't know when will that happen though. For now you can just adjust these lines and replace 10 with whatever you want.
https://github.com/GeorgeFilipkin/pulsemixer/blob/75792cc1800cf800184cf97b558e08425d879f56/pulsemixer#L1607-L1610

**Comment by GeorgeFilipkin** [comment]
Should be doable via [config](https://github.com/GeorgeFilipkin/pulsemixer#configuration) now.
See the `step-big` option.
