### ISSUE TITLE
Display only specified sink in interactive mode

### ISSUE THREAD

**Issue by squigglezworth** [GeorgeFilipkin/pulsemixer#32]
It would be very helpful to be able to specify a single sink ID to control in interactive mode.

Thoughts?

**Comment by GeorgeFilipkin** [comment]
Sorry, took me a while.

Can you elaborate on this feature and maybe give some use-cases? I don't quite understand what you had in mind.

**Comment by GeorgeFilipkin** [comment]
I'm closing this for now. Feel free to reopen if needed.
