### ISSUE TITLE
feature requert: vim style key mapping config

### ISSUE THREAD

**Issue by wis** [GeorgeFilipkin/pulsemixer#34]
I love this program, but it's quite qwertynormative.. and I use the Colemak mod DH keyboard layout.
let's make it inclusive for qwerty nonconforming folks. :)

**Comment by hberntsen** [comment]
I have a fork with hardcoded Colemak keybindings: https://github.com/hberntsen/pulsemixer . Would be nice to have official support for this.

**Comment by GeorgeFilipkin** [comment]
Should be doable via [config](https://github.com/GeorgeFilipkin/pulsemixer#configuration) now.
See the `[keys]` section.

**Comment by wis** [comment]
@GeorgeFilipkin awesome, I appreciate you making the program and now adding this feature, 
though this is not exactly vim style key binding;
I would like to map
``` cfg
mode1 = <C-o> ; Output
mode1 = <C-i> ; Input
mode3 = <C-c> ; Cards
``` 
the reason is I would like to keep my hands on the home row of the keyboard by not moving them to the distant function keys, the same reason I use pulsemixer and avoid GUI's (to keep my hands off the mouse).

**Comment by GeorgeFilipkin** [comment]
Well, combinations are a bit triciker. You also have to take into accout that <kbd>C-i</kbd> is basically Tab so that would create conflict with `next-mode = KEY_TAB`.
But I'll see what I can do.

**Comment by GeorgeFilipkin** [comment]
6fa03d7e586095a033cbd8e5e37d1b527d3b4edd brings limited support for C-key M-key binds.
You can put them in config like this: `next-mode = KEY_TAB, C-n, M-e`

- Currently only supports printable keys, i.e. <kbd>C-\<character\></kbd> will work, but binds with special keys like <kbd>C-KEY_UP</kbd> won't work.
- <kbd>C-c</kbd> is still bound to `SIGINT`.
- <kbd>C-i</kbd> still counts as Tab.

@wis I haven't tested this on non-qwerty layouts so you'll have to check if it's working properly.

**Comment by wis** [comment]
great, works on my tens in a billion keyboard layout as it should because you're not binding to keycodes. 
since `C-i` and `C-c` still can't work, I used the closest letters to the first phonemes as a mnemonic instead. 
``` cfg
mode1     = KEY_F1, C-o
mode2     = KEY_F2, C-n
mode3     = KEY_F3, C-k
```
but I don't think that I will use them, since I found out the tab switches between modes, I've have the tab key mapped to the key next to my thumb (a super key when long pressed), I always keep my second thumb on the key next to the spacebar, even though I have a normal keyboard, can't wait to get a keyboard like the ergodox or a split 40% keyboard.

even though I won't use it, can you add `prev-mode` for the sake of completeness.

**Comment by GeorgeFilipkin** [comment]
>can you add prev-mode for the sake of completeness.

Done.  
`prev-mode` in config, bound to <kbd>Shift+Tab</kbd> by default.
