### ISSUE TITLE
Show only card profiles which are available currently

### ISSUE THREAD

**Issue by aaschmid** [GeorgeFilipkin/pulsemixer#35]
Currently all the possible card profiles from `pactl list cards` are displayed in third tab "F3 Cards". I am wondering if this is attended or if it would be possible (e.g. via config file or cmd line argument) to only show currently available which can be detetcted via `pactl list cards` and searching `available` ports and their corresponding `Part fo profile(s)` properties. 

Alternatively it would make it easier to mark them differently. If you think some of this is worth implementing it, I could also start a PR after some hints provided.

Example excerpts for 

* not available:
```
hdmi-output-2: HDMI / DisplayPort 3 (priority: 5700, latency offset: 0 usec, not available)
	Properties:
		device.icon_name = "video-display"
	Part of profile(s): output:hdmi-stereo-extra2, output:hdmi-stereo-extra2+input:analog-stereo, output:hdmi-surround-extra2, output:hdmi-surround-extra2+input:analog-stereo, output:hdmi-surround71-extra2, output:hdmi-surround71-extra2+input:analog-stereo
```
* available:
```
hdmi-output-2: HDMI / DisplayPort 3 (priority: 5700, latency offset: 0 usec, available)
	Properties:
		device.icon_name = "video-display"
		device.product.name = "XXX TV"
	Part of profile(s): output:hdmi-stereo-extra2, output:hdmi-stereo-extra2+input:analog-stereo, output:hdmi-surround-extra2, output:hdmi-surround-extra2+input:analog-stereo, output:hdmi-surround71-extra2, output:hdmi-surround71-extra2+input:analog-stereo
```

`pulsemixer` always shows the same list of items, see screenshot:
![screenshot_20190101-010629](https://user-images.githubusercontent.com/567653/50569274-a43d9980-0d61-11e9-8227-4ea742655765.png)

Edit: Just saw that even the profile shows if it is `available` by displaying `yes` or `no`, see

```
output:hdmi-stereo-extra2: Digital Stereo (HDMI 3) Output (sinks: 1, sources: 0, priority: 5700, available: yes)
```
vs.
```
output:hdmi-stereo-extra2: Digital Stereo (HDMI 3) Output (sinks: 1, sources: 0, priority: 5700, available: no)
```

**Comment by GeorgeFilipkin** [comment]
Color unavailable stuff differently, maybe in red. Or append "off/unplugged" similar to what `pavucontrol` does. And give the ability to hide unavailable ports/profiles completely via config file (once the config implemented)

Yep, working on it.

**Comment by GeorgeFilipkin** [comment]
Should be doable via [config](https://github.com/GeorgeFilipkin/pulsemixer#configuration) now. 
See `hide-unavailable-profiles` and `hide-unavailable-ports` options.

**Comment by aaschmid** [comment]
Works excellent, thanks!
