### ISSUE TITLE
[Feature] Showing default sink in --list-sinks

### ISSUE THREAD

**Issue by Mange** [GeorgeFilipkin/pulsemixer#36]
It would be great if the current default sink could be listed in the `--list-sinks` output.

Perhaps like this:

```
Sink input:      ID: 3, Name: Spotify, Mute: 0, Channels: 2, Volumes: ['55%', '55%']
Sink:            ID: 0, Name: G430 Surround Sound Gaming Headset Analog stereo, Mute: 0, Channels: 2, Volumes: ['71%', '71%']
Sink:            ID: 3, Name: Built-In Analog stereo, Mute: 0, Channels: 2, Volumes: ['60%', '60%'], Default
```

(Note the added `, Default` at the end of the last line)

This would help me write a small Rofi/dmenu utility to quickly pick my default output source.

**Comment by GeorgeFilipkin** [comment]
Done.

**Comment by Mange** [comment]
Much appreciated! 😁

**Comment by GeorgeFilipkin** [comment]
There are still some features I'd like to implement before the 2.0 release. Hopefully I can get it done by the end of the next month.
