### ISSUE TITLE
Mute inputs

### ISSUE THREAD

**Issue by Teeffelen** [GeorgeFilipkin/pulsemixer#38]
How does one mute the microphone?

If it's set using the --toggle-mute ID, how do I discover which ID the mic has?

I am able to mute the mic with the interactive interface, but I'd like to create a key bind to mute it.

**Comment by GeorgeFilipkin** [comment]
`pulsemixer -l` shows the list with ids, then you take that id and do `pulsemixer --id n --toggle-mute`

I've just remembered now that PulseAudio doesn't use unique IDs and sometimes they can overlap, i.e. sink (output) and source (input) streams can have the same id and in that case priority goes to sink which results in inability to select source with --id. Yeah... I've been meaning to fix that.

**Comment by GeorgeFilipkin** [comment]
Alright, I don't know if this ID overlapping problem was relevant to you but I've changed IDs a bit to prevent this from happening. There are also now [CLI examples](https://github.com/GeorgeFilipkin/pulsemixer#cli-examples) in the README.

**Comment by crodjer** [comment]
I was able to use this to get pulsemixer to toggle the default mic:
```
pulsemixer` --toggle-mute --id $(pulsemixer --list-sources | grep Default | grep -Po "\d+" | head -1)
```
