### ISSUE TITLE
Sink selection

### ISSUE THREAD

**Issue by b3niup** [GeorgeFilipkin/pulsemixer#4]
Hi, 

It'd be awesome if there was some way to change sink for selected sink-input. 
This can be achieved by using pactl command: `pactl move-sink-input`.

Nice project btw.

Best regards,
b3niup

**Comment by GeorgeFilipkin** [comment]
Hi. And thanks. 

Yes, I thought about that. My initial idea was to have a context menu with some of pactl features, including `move-sink-input`. But I didn't think people would actually need/use it, so I dropped it.

Now, given that there is some interest - I will implement this. Not sure when, though. Not very soon.

**Comment by b3niup** [comment]
Awesome!

If I find some free time I'll try to contribute but I'm not sure if you won't be first with implementing those features ;)

**Comment by GeorgeFilipkin** [comment]
Done.
