### ISSUE TITLE
consider releasing a new version

### ISSUE THREAD

**Issue by anthraxx** [GeorgeFilipkin/pulsemixer#43]
Last release is from Dec 16, 2017, maybe its time for another one?
It would be cool to have regular updates if, like now, some small fixes and features/adjustments make it into the repo. This would allow distros to pickup those changes instead of keeping them outside of a release for over 2 years.
thanks a lot, cheers

**Comment by GeorgeFilipkin** [comment]
I was hoping to implement Peak Detect similar to what pavucontrol has, but it's taking longer than expected. I'll make a few fixes and release 1.5 without this feature then.

**Comment by GeorgeFilipkin** [comment]
https://github.com/GeorgeFilipkin/pulsemixer/releases/tag/1.5.0
