### ISSUE TITLE
Newline in file name

### ISSUE THREAD

**Issue by Diff-fusion** [GeorgeFilipkin/pulsemixer#48]
Pulsemixer crashes when playing a file with a newline in the name.

Example while playing 'te\nst.mp3' with mpv:
![123_000](https://user-images.githubusercontent.com/47172717/79005066-5dd70d00-7b56-11ea-8317-21e6ad637aae.png)

**Comment by GeorgeFilipkin** [comment]
Thanks. Should work now.
