### ISSUE TITLE
Inactivity

### ISSUE THREAD

**Issue by sewnie** [GeorgeFilipkin/pulsemixer#65]
this amazing tool that is extremely useful and an replacement for pavucontrol and alsamixer

the problem is that this has not been updated since april of 2020 and many issues and pull requests have just not been getting any attention,
the last solved issue was last year, i'm also dealing with an issue but i assume it won't be fixed because of font rendering in pulsemixer

the project owner [GeorgeFilipkin](https://github.com/GeorgeFilipkin) has also been inactive, i would love to see if the project got updated this year

**Comment by port19x** [comment]
It might be time to fork the project or work on a drop-in replacement for the tool if the inactivity continues like this.
With all due respect, writing and maintaining a python curses interface can't be that difficult. On the other hand working with pulseaudio, even as an enduser, can be quite frustrating

**Comment by port19x** [comment]
It seems like a complete rewrite would be easier

**Comment by sewnie** [comment]
considering i made that issue with no knowledge of C, i think i can try to do this, although i believe it is quite uneccessary considering `wpctl` exists.

**Comment by sewnie** [comment]
related: #70

**Comment by port19x** [comment]
> considering i made that issue with no knowledge of C, i think i can try to do this, although i believe it is quite uneccessary considering `wpctl` exists.

`wpctl` is a cli instead of a tui, which leaves some room in the market for a `pipemixer`.
How important that is as a program is up for debate tho, I wouldn't waste my time

**Comment by iconoclasthero** [comment]
> > considering i made that issue with no knowledge of C, i think i can try to do this, although i believe it is quite uneccessary considering `wpctl` exists.
> 
> `wpctl` is a cli instead of a tui, which leaves some room in the market for a `pipemixer`. How important that is as a program is up for debate tho, I wouldn't waste my time

Is there a cli/tui pipemixer?

**Comment by sewnie** [comment]
#70
